<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linguaflow.DAL\Linguaflow.DAL.csproj" />
    <ProjectReference Include="..\LinguaFlow.Models\LinguaFlow.Models.csproj" />
  </ItemGroup>

</Project>
